theme: jekyll-theme-minimal

# Name of website
title: Rafael Charris

# Your name to show in the footer
author: Rafael Charris

navbar-links:
  About Me: "aboutme"
  My Blog: UnbiasedDataBlog.github.io
  Resources:
  - Learn markdown: "https://www.markdowntutorial.com/"

social-network-links:
  email: "rafaelcharris92@gmail.com"
  github: rafaelcharris
  twitter: daattali
  
# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

